version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - echo "NVM install"
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' # This loads nvm
      - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' # This loads nvm bash_completion
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      - $(aws ecr get-login --no-include-email --region ${region})

      - REPOSITORY_URI=${ecr_api_repository_url}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - IMAGE_TAG=$${COMMIT_HASH}
  build:
    on-failure: ABORT
    commands:
      - echo "Make DATABASEURL env var for prisma"
      - echo "DATABASE_URL=$DATABASE_URL" > .env
      - . "$NVM_DIR/nvm.sh" && nvm install 16
      - . "$NVM_DIR/nvm.sh" && nvm use 16
      - echo "Build a service"
      - yarn install
      # Prisma generate and GraphQL Schema generate
      - yarn generate
      # Type Check
      - yarn typecheck
      # Unit Test
      - NODE_ENV=test yarn test --collectCoverage
      # TypeScript build
      - yarn build
      # Database migration by using Prisma Engine. DATABASE_URL should be specified in environment.
      - yarn prisma migrate deploy
      # GraphQL schema send to Apollo Studio
      - yarn rover subgraph publish ${apollo_graph_ref} --name mystack --schema ./src/generated/schema.graphql --routing-url ${api_endpoint_url}
      # Build Docker image
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --cache-from ${ecr_api_repository_url}:latest -t ${api_repository_name} .
      - docker tag ${api_repository_name}:latest ${ecr_api_repository_url}:latest

      - docker build -t ${api_repository_name}:latest .
      - docker tag ${api_repository_name}:latest ${ecr_api_repository_url}:$${IMAGE_TAG}
  post_build:
    on-failure: ABORT
    commands:
      - echo Pushing the Docker images...
      - docker push ${ecr_api_repository_url}:latest
      - docker push ${ecr_api_repository_url}:$${IMAGE_TAG}
      - echo Writing image definitions file...
      - aws ecs describe-task-definition --task-definition ${task_definition} | jq '.taskDefinition' > taskdef.json
      - envsubst < appspec_template.yaml > appspec.yaml
      - printf '[{"name":"api","imageUri":"%s"}]' ${ecr_api_repository_url}:latest > apiimagedefinitions.json
artifacts:
  files:
    - appspec.yaml
    - apiimagedefinitions.json
    - taskdef.json
# reports:
#   jest_reports:
#     files:
#       - testResult.xml
#     file-format: JUNITXML
#     base-directory: .report
#   coverage_reports:
#     files:
#       - coverage/clover.xml
#     file-format: CLOVERXML
